### ISSUE TITLE
[FEATURE] Release a new version for the performance-analyzer-commons repo 

### ISSUE THREAD

**Issue by Divyaasm** [opensearch-project/performance-analyzer-commons#60]
**Is your feature request related to a problem?**
The current version 1.1.0 of [performance-analyzer-commons](https://github.com/opensearch-project/performance-analyzer-commons) repo is causing performance-analyzer build failure.

**What solution would you like?**
Release a new version to create a tag with the [commit](https://github.com/opensearch-project/performance-analyzer-commons/commit/83cb2d427f28c9e814150d079f32be1a88b41446) that's causing the 2.11.1 build failure.
 
**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by acidul** [comment]
Hello, 
the issue also exists on performance-analyzer 2.10.0.

It fails with following errors : 
> Task :compileJava
/workspaces/performance-analyzer/src/main/java/org/opensearch/performanceanalyzer/collectors/ClusterManagerServiceEventMetrics.java:8: error: cannot find symbol
import static org.opensearch.performanceanalyzer.commons.stats.metrics.StatExceptionCode.CLUSTER_MANAGER_METRICS_ERROR;
^
  symbol:   static CLUSTER_MANAGER_METRICS_ERROR
  location: enum StatExceptionCode
/workspaces/performance-analyzer/src/main/java/org/opensearch/performanceanalyzer/collectors/ClusterManagerServiceMetrics.java:8: error: cannot find symbol
import static org.opensearch.performanceanalyzer.commons.stats.metrics.StatExceptionCode.CLUSTER_MANAGER_METRICS_ERROR;
^
  symbol:   static CLUSTER_MANAGER_METRICS_ERROR
  location: enum StatExceptionCode
/workspaces/performance-analyzer/src/main/java/org/opensearch/performanceanalyzer/collectors/ClusterManagerServiceEventMetrics.java:54: error: cannot find symbol
                CLUSTER_MANAGER_METRICS_ERROR);
                ^
  symbol:   variable CLUSTER_MANAGER_METRICS_ERROR
  location: class ClusterManagerServiceEventMetrics
/workspaces/performance-analyzer/src/main/java/org/opensearch/performanceanalyzer/collectors/ClusterManagerServiceEventMetrics.java:166: error: cannot find symbol
            StatsCollector.instance().logException(CLUSTER_MANAGER_METRICS_ERROR);
                                                   ^
  symbol:   variable CLUSTER_MANAGER_METRICS_ERROR
  location: class ClusterManagerServiceEventMetrics
/workspaces/performance-analyzer/src/main/java/org/opensearch/performanceanalyzer/collectors/ClusterManagerServiceMetrics.java:42: error: cannot find symbol
                CLUSTER_MANAGER_METRICS_ERROR);
                ^
  symbol:   variable CLUSTER_MANAGER_METRICS_ERROR
  location: class ClusterManagerServiceMetrics
Note: /workspaces/performance-analyzer/src/main/java/org/opensearch/performanceanalyzer/http_action/config/PerformanceAnalyzerClusterConfigAction.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
5 errors

where performance-analyzer-commons is :
/root/.gradle/caches/modules-2/files-2.1/org.opensearch/performance-analyzer-commons/1.1.0-SNAPSHOT/27b636a9114e1092fb9b49224c1a5c9f24d30d37/performance-analyzer-commons-1.1.0-SNAPSHOT.jar
