### ISSUE TITLE
[migration] to mockito v5 from v2

### ISSUE THREAD

**Issue by DesmondWillowbrook** [opensearch-project/performance-analyzer-commons#70]
The main [OpenSearch repository](https://github.com/opensearch-project/OpenSearch) uses Mockito 5 while PA is currently using Mockito 2. Mockito 5 removes the need to use PowerMock, thus eliminating one of our test dependencies and contains new functionality that may be useful for writing unit tests.

This can help #69 since we will be upgrading to a more recent test framework with more features.

In particular, [this file in the OpenSearch repository](https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/version.properties) contains the version numbers for mockito and other packages.

**Comment by DesmondWillowbrook** [comment]
I am working on this.

**Comment by DesmondWillowbrook** [comment]
This issue is open to contributions.

Relevant information:
- [Mockito mockStatic](https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#48) to replace `PowerMockito.mockStatic`
- [Mockito mockConstruction](https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#mocked_construction) to replace `PowerMockito.whenNew`.

**Comment by dblock** [comment]
[Triage -- attendees [1](https://github.com/dblock), [2](https://github.com/peternied), [3](https://github.com/reta), [4](https://github.com/krisfreedain), [5](https://github.com/Getsaurabh02), [6](https://github.com/gkamat), [7](https://github.com/scrawfor99)]

@DesmondWillowbrook Are you still trying to do this?
